deployement:
  replicas: 1
  imageUrl: 824333137275.dkr.ecr.us-east-1.amazonaws.com/roboshop/catalogue
  imageVersion: IMAGE_VERSION
service:
  targetPort: 8080
configMap:
  MONGO_URL: "mongodb://mongodb:27017/catalogue"